Name:           ros-jade-opencv3
Version:        3.2.0
Release:        2%{?dist}
Summary:        ROS opencv3 package

Group:          Development/Libraries
License:        BSD
URL:            http://opencv.org
Source0:        %{name}-%{version}.tar.gz

Requires:       ffmpeg-devel
Requires:       jasper-devel
Requires:       libjpeg-turbo-devel
Requires:       libpng12-devel
Requires:       numpy
Requires:       protobuf
Requires:       python-devel
Requires:       ros-jade-catkin
Requires:       vtk-qt
Requires:       zlib-devel
BuildRequires:  cmake
BuildRequires:  ffmpeg-devel
BuildRequires:  jasper-devel
BuildRequires:  libjpeg-turbo-devel
BuildRequires:  libpng12-devel
BuildRequires:  libtiff
BuildRequires:  libv4l-devel
BuildRequires:  numpy
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel
BuildRequires:  python-devel
BuildRequires:  vtk-qt
BuildRequires:  zlib-devel

%description
OpenCV 3.x

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Mon Feb 27 2017 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.2.0-2
- Autogenerated by Bloom

* Sun Feb 26 2017 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.2.0-1
- Autogenerated by Bloom

* Sun Jan 29 2017 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.2.0-0
- Autogenerated by Bloom

* Thu Dec 31 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.1.0-1
- Autogenerated by Bloom

* Thu Dec 31 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.1.0-0
- Autogenerated by Bloom

* Sun Dec 20 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.0.0-11
- Autogenerated by Bloom

* Sun Dec 06 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.0.0-10
- Autogenerated by Bloom

* Wed Oct 21 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.0.0-9
- Autogenerated by Bloom

* Sat Sep 26 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.0.0-8
- Autogenerated by Bloom

* Sat Sep 26 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.0.0-7
- Autogenerated by Bloom

* Sat Sep 26 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.0.0-6
- Autogenerated by Bloom

* Sat Sep 26 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.0.0-5
- Autogenerated by Bloom

* Sat Sep 26 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 3.0.0-4
- Autogenerated by Bloom

